" General Options
"===================
" key mappings
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-h> <c-w>h
map <c-l> <c-w>l
map <c-w>r :vertical resize 80<CR>

map <space> <leader>
map <leader><space> :nohlsearch<CR>
nnoremap <leader><return> :wa!<CR>

set list
set listchars=tab:>.,trail:.
set colorcolumn=81
set showbreak=\ #>
set hlsearch
set expandtab
set tabstop=4
set shiftwidth=4
set number
set ruler

" disable bells
set noeb vb t_vb=
au GUIEnter * set vb t_vb=

" move by displayed lines
nnoremap <silent> <Up> gk
nnoremap <silent> <Down> gj
nnoremap <silent> <Home> g<Home>
nnoremap <silent> <End> g<End>
nnoremap <silent> k gk
nnoremap <silent> j gj
nnoremap <silent> 0 g0
nnoremap <silent> $ g$
inoremap <silent> <Up> <C-o>gk
inoremap <silent> <Down> <C-o>gj
inoremap <silent> <Home> <C-o>g<Home>
inoremap <silent> <End> <C-o>g<End>

" save swapfiles in .vim directory instead of leaving them lying around
if ! has('nvim')
    set directory=~/.vim/swap//
    set backupdir=~/.vim/swap/backup//
    set undodir=~/.vim/swap/undo//
endif

" filetype options
autocmd Filetype html* setlocal expandtab tabstop=2 shiftwidth=2
au BufRead,BufNewFile *.html.template set filetype=mako
