# This file just sources all the files in .bashrc.d
# Don't add actual configuration here, add it to a script in .bashrc.d!
# (And don't forget to make it -x)
source_all() {
  if [[ -d "$1" ]]; then
    for script in "$1"/*; do
      [ -x "$script" ] && source "$script"
    done
  else
    echo "$1 is not a directory!" >&2
    return 1
  fi
}

source_all ~/.bashrc.d
